CREATE TABLE lists (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE
);

CREATE TABLE todos(
  id SERIAL PRIMARY KEY,
  list_id INTEGER NOT NULL REFERENCES lists(id),
  name VARCHAR NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);
